# Knative Language Configuration
# All nl configurations are set here.
# Note: NL source is maintained in the translations branch of the knative/docs repo:
# <TODO Create branch for nls> https://github.com/knative/docs/tree/translations) </TODO>

[en]
  title = "Knative"
  description = "Knative provides a set of components for building modern, source-centric, and container-based applications that can run anywhere."
  languageName = "English"
  contentDir = "content/en"
  # Weight used for sorting.
  weight = 1
  time_format_default = "02.01.2006"
  time_format_blog = "02.01.2006"

# Template/example for additional NLs
# (where translated source is "content/[LANG]" and config file is "il8n/[LANG].toml")
#
# Example: LANG = ja (Japanese):
#
# [ja]
#   title = "Knative"
#   description = "Knative [ja translation here]"
#   languageName = "Japanese"
#   contentDir = "content/ja"
#   weight = 2
#   time_format_default = "2006.02.01"
#   time_format_blog = "2006.02.01"
